language: php

php:
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_script:
  - '[ "7.0" = "$(phpenv version-name)" ] && composer require satooshi/php-coveralls:dev-master && vendor/bin/coveralls -v'
